version: "3.2"

services:
    nginx:
        build:
            context: ./docker/dev
            dockerfile: nginx.dockerfile
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-cli:
        build:
            context: ./docker
            dockerfile: ./dev/php-cli.dockerfile
        environment:
            APP_DEBUG: 1
        volumes:
            - ./:/app
            - ${HOME}/.composer:/.composer
    php-fpm:
        build:
            context: ./docker
            dockerfile: ./dev/php-fpm.dockerfile
        environment:
            APP_DEBUG: 1
        volumes:
            - ./:/app
    postgres:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_USER: muellerdict
            POSTGRES_PASSWORD: password
            POSTGRES_DB: muellerdict
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

volumes:
    composer:
    postgres:

