version: "3.2"

services:
    nginx:
        build:
            context: ./docker/dev
            dockerfile: nginx.dockerfile
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-cli:
        build:
            context: ./docker
            dockerfile: ./dev/php-cli.dockerfile
        environment:
            APP_DEBUG: 1
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
            - ./:/app
            - ${HOME}/.composer:/.composer
    php-fpm:
        build:
            context: ./docker
            dockerfile: ./dev/php-fpm.dockerfile
        environment:
            APP_DEBUG: 1
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
            - ./:/app
    postgres:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_USER: muellerdict
            POSTGRES_PASSWORD: password
            POSTGRES_DB: muellerdict
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"
    adminer:
        image: adminer
        depends_on:
            - postgres
        environment:
            ADMINER_DEFAULT_DB_DRIVER: pgsql
            ADMINER_DEFAULT_DB_HOST: postgres
            ADMINER_DEFAULT_DB_NAME: muellerdict
        ports:
            - 8085:8080

volumes:
    composer:
    postgres:

