version: "3.2"

services:
    nginx:
        build:
            context: ./docker/dev
            dockerfile: nginx.dockerfile
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-cli:
        build:
            context: ./docker
            dockerfile: ./dev/php-cli.dockerfile
        environment:
            APP_DEBUG: 1
        volumes:
            - ./:/app
            - ${HOME}/.composer:/.composer
    php-fpm:
        build:
            context: ./docker
            dockerfile: ./dev/php-fpm.dockerfile
        environment:
            APP_DEBUG: 1
        volumes:
            - ./:/app

volumes:
    composer:
